### ISSUE TITLE
Requires patches on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [videolabs/libmicrodns#39] opened 2020-10-29 02:46 UTC
I had to apply these patches to build on FreeBSD 12.2:

```
--- include/microdns/rr.h.orig	2020-10-29 02:44:44 UTC
+++ include/microdns/rr.h
@@ -35,6 +35,8 @@
 # include <ws2tcpip.h>
 #endif
 
+#include <netinet/in.h>
+
 # ifdef __cplusplus
 extern "C" {
 # endif
--- include/utils.h.orig	2020-10-29 02:42:44 UTC
+++ include/utils.h
@@ -31,6 +31,8 @@
 #include <stdio.h>
 #include <stdint.h>
 
+#include <netinet/in.h>
+
 #include "compat.h"
 
 #define MDNS_DN_MAXSZ 256 // domain name maximum size
--- src/rr.c.orig	2020-10-29 02:40:53 UTC
+++ src/rr.c
@@ -32,6 +32,8 @@
 #include <stdlib.h>
 #include <stdint.h>
 
+#include <netinet/in.h>
+
 #include "utils.h"
 #include "microdns/microdns.h"
 #include "microdns/rr.h"
```

**Comment by jbkempf** [comment] 2022-05-27 12:10
Duplicate of #38

**Closed as completed by jbkempf** 2022-05-27 12:11 UTC

**Comment by yurivict** [comment] 2022-05-27 18:50
I made corrections.

**Comment by jbkempf** [comment] 2022-05-27 19:06
> I made corrections.

Cool. Merged.
